# coding: utf-8

"""
    Production

    Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredMetricShowSummaryResponseMetricsItem(TypedDict):
    pass

class OptionalMetricShowSummaryResponseMetricsItem(TypedDict, total=False):
    human_date: str

    date: int

    active_customers: int

    active_subscriptions: int

    add_on_mrr: int

    arpu: int

    arr: int

    cancellations: int

    coupons: int

    downgrades: int

    failed_charges: int

    fees: int

    ltv: int

    mrr: int

    net_revenue: int

    new_customers: int

    other_revenue: int

    reactivated_customers: int

    refunds: int

    revenue_churn: int

    trial_conversions: int

    upgrades: int

    user_churn: int

class MetricShowSummaryResponseMetricsItem(RequiredMetricShowSummaryResponseMetricsItem, OptionalMetricShowSummaryResponseMetricsItem):
    pass
