# coding: utf-8

# flake8: noqa

"""
    Production

    Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0"

# import ApiClient
from baremetrics_python_sdk.api_client import ApiClient

# import Configuration
from baremetrics_python_sdk.configuration import Configuration

# import exceptions
from baremetrics_python_sdk.exceptions import OpenApiException
from baremetrics_python_sdk.exceptions import ApiAttributeError
from baremetrics_python_sdk.exceptions import ApiTypeError
from baremetrics_python_sdk.exceptions import ApiValueError
from baremetrics_python_sdk.exceptions import ApiKeyError
from baremetrics_python_sdk.exceptions import ApiException

from baremetrics_python_sdk.client import Baremetrics
