# coding: utf-8
"""
    Production

    Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from baremetrics_python_sdk.client_custom import ClientCustom
from baremetrics_python_sdk.configuration import Configuration
from baremetrics_python_sdk.api_client import ApiClient
from baremetrics_python_sdk.type_util import copy_signature
from baremetrics_python_sdk.apis.tags.account_api import AccountApi
from baremetrics_python_sdk.apis.tags.annotation_api import AnnotationApi
from baremetrics_python_sdk.apis.tags.attribute_api import AttributeApi
from baremetrics_python_sdk.apis.tags.cancellation_insight_api import CancellationInsightApi
from baremetrics_python_sdk.apis.tags.event_api import EventApi
from baremetrics_python_sdk.apis.tags.goal_api import GoalApi
from baremetrics_python_sdk.apis.tags.metric_api import MetricApi
from baremetrics_python_sdk.apis.tags.reason_api import ReasonApi
from baremetrics_python_sdk.apis.tags.segment_api import SegmentApi
from baremetrics_python_sdk.apis.tags.source_api import SourceApi
from baremetrics_python_sdk.apis.tags.user_api import UserApi



class Baremetrics(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.account: AccountApi = AccountApi(api_client)
        self.annotation: AnnotationApi = AnnotationApi(api_client)
        self.attribute: AttributeApi = AttributeApi(api_client)
        self.cancellation_insight: CancellationInsightApi = CancellationInsightApi(api_client)
        self.event: EventApi = EventApi(api_client)
        self.goal: GoalApi = GoalApi(api_client)
        self.metric: MetricApi = MetricApi(api_client)
        self.reason: ReasonApi = ReasonApi(api_client)
        self.segment: SegmentApi = SegmentApi(api_client)
        self.source: SourceApi = SourceApi(api_client)
        self.user: UserApi = UserApi(api_client)
