# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from baremetrics_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    V1_ACCOUNT = "/v1/account"
    V1_SOURCES = "/v1/sources"
    V1_SOURCE_ID_PLANS = "/v1/{source_id}/plans"
    V1_SOURCE_ID_PLANS_OID = "/v1/{source_id}/plans/{oid}"
    V1_SOURCE_ID_PLANS_PLAN_OID = "/v1/{source_id}/plans/{plan_oid}"
    V1_SOURCE_ID_CUSTOMERS = "/v1/{source_id}/customers"
    V1_SOURCE_ID_CUSTOMERS_OID = "/v1/{source_id}/customers/{oid}"
    V1_SOURCE_ID_CUSTOMERS_OID_EVENTS = "/v1/{source_id}/customers/{oid}/events"
    V1_SOURCE_ID_CUSTOMERS_CUSTOMER_OID = "/v1/{source_id}/customers/{customer_oid}"
    V1_SOURCE_ID_SUBSCRIPTIONS = "/v1/{source_id}/subscriptions"
    V1_SOURCE_ID_SUBSCRIPTIONS_OID = "/v1/{source_id}/subscriptions/{oid}"
    V1_SOURCE_ID_SUBSCRIPTIONS_SUBSCRIPTION_OID = "/v1/{source_id}/subscriptions/{subscription_oid}"
    V1_SOURCE_ID_SUBSCRIPTIONS_SUBSCRIPTION_OID_CANCEL = "/v1/{source_id}/subscriptions/{subscription_oid}/cancel"
    V1_ANNOTATIONS = "/v1/annotations"
    V1_ANNOTATIONS_ID = "/v1/annotations/{id}"
    V1_GOALS = "/v1/goals"
    V1_GOALS_ID = "/v1/goals/{id}"
    V1_USERS = "/v1/users"
    V1_USERS_ID = "/v1/users/{id}"
    V1_SOURCE_ID_CHARGES = "/v1/{source_id}/charges"
    V1_SOURCE_ID_CHARGES_OID = "/v1/{source_id}/charges/{oid}"
    V1_SOURCE_ID_REFUNDS = "/v1/{source_id}/refunds"
    V1_SOURCE_ID_REFUNDS_OID = "/v1/{source_id}/refunds/{oid}"
    V1_SOURCE_ID_EVENTS = "/v1/{source_id}/events"
    V1_SOURCE_ID_EVENTS_ID = "/v1/{source_id}/events/{id}"
    V1_METRICS = "/v1/metrics"
    V1_METRICS_METRIC = "/v1/metrics/{metric}"
    V1_METRICS_METRIC_CUSTOMERS = "/v1/metrics/{metric}/customers"
    V1_METRICS_METRIC_PLANS = "/v1/metrics/{metric}/plans"
    V1_METRICS_COHORTS = "/v1/metrics/cohorts"
    V1_SEGMENTS_FIELDS = "/v1/segments/fields"
    V1_SEGMENTS = "/v1/segments"
    V1_SEGMENTS_ID = "/v1/segments/{id}"
    V1_SEGMENTS_SEARCH = "/v1/segments/search"
    V1_ATTRIBUTES = "/v1/attributes"
    V1_ATTRIBUTES_FIELDS = "/v1/attributes/fields"
    V1_ATTRIBUTES_FIELDS_ID = "/v1/attributes/fields/{id}"
    V1_CANCELLATION_INSIGHTS_EVENTS = "/v1/cancellation_insights/events"
    V1_CANCELLATION_INSIGHTS_EVENTS_ID = "/v1/cancellation_insights/events/{id}"
    V1_CANCELLATION_INSIGHTS_REASONS_ID = "/v1/cancellation_insights/reasons/{id}"
    V1_CANCELLATION_INSIGHTS_REASONS = "/v1/cancellation_insights/reasons"
