# coding: utf-8

"""
    Production

    Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from baremetrics_python_sdk import schemas  # noqa: F401


class GoalCreateNewGoalRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "end_date",
            "metric",
            "name",
            "start_amount",
            "end_amount",
            "start_date",
        }
        
        class properties:
            metric = schemas.StrSchema
            start_amount = schemas.Int32Schema
            end_amount = schemas.Int32Schema
            start_date = schemas.DateSchema
            end_date = schemas.DateSchema
            name = schemas.StrSchema
            __annotations__ = {
                "metric": metric,
                "start_amount": start_amount,
                "end_amount": end_amount,
                "start_date": start_date,
                "end_date": end_date,
                "name": name,
            }
    
    end_date: MetaOapg.properties.end_date
    metric: MetaOapg.properties.metric
    name: MetaOapg.properties.name
    start_amount: MetaOapg.properties.start_amount
    end_amount: MetaOapg.properties.end_amount
    start_date: MetaOapg.properties.start_date
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metric"]) -> MetaOapg.properties.metric: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["start_amount"]) -> MetaOapg.properties.start_amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["end_amount"]) -> MetaOapg.properties.end_amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["start_date"]) -> MetaOapg.properties.start_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["end_date"]) -> MetaOapg.properties.end_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["metric", "start_amount", "end_amount", "start_date", "end_date", "name", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metric"]) -> MetaOapg.properties.metric: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["start_amount"]) -> MetaOapg.properties.start_amount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["end_amount"]) -> MetaOapg.properties.end_amount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["start_date"]) -> MetaOapg.properties.start_date: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["end_date"]) -> MetaOapg.properties.end_date: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["metric", "start_amount", "end_amount", "start_date", "end_date", "name", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        end_date: typing.Union[MetaOapg.properties.end_date, str, date, ],
        metric: typing.Union[MetaOapg.properties.metric, str, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        start_amount: typing.Union[MetaOapg.properties.start_amount, decimal.Decimal, int, ],
        end_amount: typing.Union[MetaOapg.properties.end_amount, decimal.Decimal, int, ],
        start_date: typing.Union[MetaOapg.properties.start_date, str, date, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'GoalCreateNewGoalRequest':
        return super().__new__(
            cls,
            *args,
            end_date=end_date,
            metric=metric,
            name=name,
            start_amount=start_amount,
            end_amount=end_amount,
            start_date=start_date,
            _configuration=_configuration,
            **kwargs,
        )
