# coding: utf-8

"""
    Production

    Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from baremetrics_python_sdk import schemas  # noqa: F401


class SourceCreateSubscriptionRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "plan_oid",
            "customer_oid",
            "started_at",
            "oid",
        }
        
        class properties:
            oid = schemas.StrSchema
            started_at = schemas.DateTimeSchema
            plan_oid = schemas.StrSchema
            customer_oid = schemas.StrSchema
            canceled_at = schemas.DateTimeSchema
        
            @staticmethod
            def addons() -> typing.Type['SourceCreateSubscriptionRequestAddons']:
                return SourceCreateSubscriptionRequestAddons
            quantity = schemas.Int32Schema
            discount = schemas.Int32Schema
            __annotations__ = {
                "oid": oid,
                "started_at": started_at,
                "plan_oid": plan_oid,
                "customer_oid": customer_oid,
                "canceled_at": canceled_at,
                "addons": addons,
                "quantity": quantity,
                "discount": discount,
            }
    
    plan_oid: MetaOapg.properties.plan_oid
    customer_oid: MetaOapg.properties.customer_oid
    started_at: MetaOapg.properties.started_at
    oid: MetaOapg.properties.oid
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["oid"]) -> MetaOapg.properties.oid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["started_at"]) -> MetaOapg.properties.started_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["plan_oid"]) -> MetaOapg.properties.plan_oid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customer_oid"]) -> MetaOapg.properties.customer_oid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["canceled_at"]) -> MetaOapg.properties.canceled_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["addons"]) -> 'SourceCreateSubscriptionRequestAddons': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["quantity"]) -> MetaOapg.properties.quantity: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["discount"]) -> MetaOapg.properties.discount: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["oid", "started_at", "plan_oid", "customer_oid", "canceled_at", "addons", "quantity", "discount", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["oid"]) -> MetaOapg.properties.oid: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["started_at"]) -> MetaOapg.properties.started_at: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["plan_oid"]) -> MetaOapg.properties.plan_oid: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customer_oid"]) -> MetaOapg.properties.customer_oid: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["canceled_at"]) -> typing.Union[MetaOapg.properties.canceled_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["addons"]) -> typing.Union['SourceCreateSubscriptionRequestAddons', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["quantity"]) -> typing.Union[MetaOapg.properties.quantity, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["discount"]) -> typing.Union[MetaOapg.properties.discount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["oid", "started_at", "plan_oid", "customer_oid", "canceled_at", "addons", "quantity", "discount", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        plan_oid: typing.Union[MetaOapg.properties.plan_oid, str, ],
        customer_oid: typing.Union[MetaOapg.properties.customer_oid, str, ],
        started_at: typing.Union[MetaOapg.properties.started_at, str, datetime, ],
        oid: typing.Union[MetaOapg.properties.oid, str, ],
        canceled_at: typing.Union[MetaOapg.properties.canceled_at, str, datetime, schemas.Unset] = schemas.unset,
        addons: typing.Union['SourceCreateSubscriptionRequestAddons', schemas.Unset] = schemas.unset,
        quantity: typing.Union[MetaOapg.properties.quantity, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        discount: typing.Union[MetaOapg.properties.discount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SourceCreateSubscriptionRequest':
        return super().__new__(
            cls,
            *args,
            plan_oid=plan_oid,
            customer_oid=customer_oid,
            started_at=started_at,
            oid=oid,
            canceled_at=canceled_at,
            addons=addons,
            quantity=quantity,
            discount=discount,
            _configuration=_configuration,
            **kwargs,
        )

from baremetrics_python_sdk.model.source_create_subscription_request_addons import SourceCreateSubscriptionRequestAddons
