# coding: utf-8

"""
    Production

    Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from baremetrics_python_sdk.paths.v1_metrics_metric_customers.get import ListCustomersRaw
from baremetrics_python_sdk.paths.v1_metrics_cohorts.get import ShowCohortsRaw
from baremetrics_python_sdk.paths.v1_metrics_metric.get import ShowDetailsRaw
from baremetrics_python_sdk.paths.v1_metrics_metric_plans.get import ShowPlanBreakoutRaw
from baremetrics_python_sdk.paths.v1_metrics.get import ShowSummaryRaw


class MetricApiRaw(
    ListCustomersRaw,
    ShowCohortsRaw,
    ShowDetailsRaw,
    ShowPlanBreakoutRaw,
    ShowSummaryRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
