# coding: utf-8

"""
    Production

    Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from baremetrics_python_sdk.paths.v1_metrics_metric_customers.get import ListCustomers
from baremetrics_python_sdk.paths.v1_metrics_cohorts.get import ShowCohorts
from baremetrics_python_sdk.paths.v1_metrics_metric.get import ShowDetails
from baremetrics_python_sdk.paths.v1_metrics_metric_plans.get import ShowPlanBreakout
from baremetrics_python_sdk.paths.v1_metrics.get import ShowSummary
from baremetrics_python_sdk.apis.tags.metric_api_raw import MetricApiRaw


class MetricApi(
    ListCustomers,
    ShowCohorts,
    ShowDetails,
    ShowPlanBreakout,
    ShowSummary,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: MetricApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = MetricApiRaw(api_client)
