# coding: utf-8

"""
    Production

    Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from baremetrics_python_sdk.paths.v1_segments.post import CreateRequest
from baremetrics_python_sdk.paths.v1_segments_search.post import FindWithoutSave
from baremetrics_python_sdk.paths.v1_segments_fields.get import GetFields
from baremetrics_python_sdk.paths.v1_segments.get import ListSegments
from baremetrics_python_sdk.paths.v1_segments_id.delete import RemoveById
from baremetrics_python_sdk.paths.v1_segments_id.get import ShowDetails
from baremetrics_python_sdk.paths.v1_segments_id.put import UpdateById
from baremetrics_python_sdk.apis.tags.segment_api_raw import SegmentApiRaw


class SegmentApi(
    CreateRequest,
    FindWithoutSave,
    GetFields,
    ListSegments,
    RemoveById,
    ShowDetails,
    UpdateById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SegmentApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SegmentApiRaw(api_client)
