# coding: utf-8

"""
    Production

    Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from baremetrics_python_sdk.paths.v1_source_id_subscriptions_subscription_oid_cancel.put import CancelSubscription
from baremetrics_python_sdk.paths.v1_source_id_charges.post import CreateChargeOneOff
from baremetrics_python_sdk.paths.v1_source_id_customers.post import CreateCustomerRecord
from baremetrics_python_sdk.paths.v1_source_id_refunds.post import CreateOneOffRefund
from baremetrics_python_sdk.paths.v1_source_id_plans.post import CreatePlan
from baremetrics_python_sdk.paths.v1_source_id_subscriptions.post import CreateSubscription
from baremetrics_python_sdk.paths.v1_source_id_customers_oid.delete import DeleteCustomer
from baremetrics_python_sdk.paths.v1_source_id_plans_oid.delete import DeletePlan
from baremetrics_python_sdk.paths.v1_source_id_charges_oid.get import GetChargeDetails
from baremetrics_python_sdk.paths.v1_source_id_charges.get import GetChargeList
from baremetrics_python_sdk.paths.v1_source_id_customers_oid.get import GetCustomerDetails
from baremetrics_python_sdk.paths.v1_source_id_customers.get import GetCustomerList
from baremetrics_python_sdk.paths.v1_source_id_events_id.get import GetEventById
from baremetrics_python_sdk.paths.v1_source_id_events.get import GetEvents
from baremetrics_python_sdk.paths.v1_source_id_plans_oid.get import GetPlan
from baremetrics_python_sdk.paths.v1_source_id_plans.get import GetPlansList
from baremetrics_python_sdk.paths.v1_source_id_refunds_oid.get import GetRefundDetails
from baremetrics_python_sdk.paths.v1_source_id_refunds.get import GetRefunds
from baremetrics_python_sdk.paths.v1_source_id_subscriptions_oid.get import GetSubscription
from baremetrics_python_sdk.paths.v1_source_id_subscriptions.get import GetSubscriptions
from baremetrics_python_sdk.paths.v1_source_id_customers_oid_events.get import ListCustomerEvents
from baremetrics_python_sdk.paths.v1_sources.get import ListSources
from baremetrics_python_sdk.paths.v1_source_id_charges_oid.delete import RemoveOneOffCharge
from baremetrics_python_sdk.paths.v1_source_id_refunds_oid.delete import RemoveOneOffRefund
from baremetrics_python_sdk.paths.v1_source_id_subscriptions_oid.delete import RemoveSubscription
from baremetrics_python_sdk.paths.v1_source_id_customers_customer_oid.put import UpdateCustomerInformation
from baremetrics_python_sdk.paths.v1_source_id_plans_plan_oid.put import UpdatePlan
from baremetrics_python_sdk.paths.v1_source_id_subscriptions_subscription_oid.put import UpdateSubscription
from baremetrics_python_sdk.apis.tags.source_api_raw import SourceApiRaw


class SourceApi(
    CancelSubscription,
    CreateChargeOneOff,
    CreateCustomerRecord,
    CreateOneOffRefund,
    CreatePlan,
    CreateSubscription,
    DeleteCustomer,
    DeletePlan,
    GetChargeDetails,
    GetChargeList,
    GetCustomerDetails,
    GetCustomerList,
    GetEventById,
    GetEvents,
    GetPlan,
    GetPlansList,
    GetRefundDetails,
    GetRefunds,
    GetSubscription,
    GetSubscriptions,
    ListCustomerEvents,
    ListSources,
    RemoveOneOffCharge,
    RemoveOneOffRefund,
    RemoveSubscription,
    UpdateCustomerInformation,
    UpdatePlan,
    UpdateSubscription,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SourceApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SourceApiRaw(api_client)
