# coding: utf-8

"""
    Production

    Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from baremetrics_python_sdk.paths.v1_source_id_subscriptions_subscription_oid_cancel.put import CancelSubscriptionRaw
from baremetrics_python_sdk.paths.v1_source_id_charges.post import CreateChargeOneOffRaw
from baremetrics_python_sdk.paths.v1_source_id_customers.post import CreateCustomerRecordRaw
from baremetrics_python_sdk.paths.v1_source_id_refunds.post import CreateOneOffRefundRaw
from baremetrics_python_sdk.paths.v1_source_id_plans.post import CreatePlanRaw
from baremetrics_python_sdk.paths.v1_source_id_subscriptions.post import CreateSubscriptionRaw
from baremetrics_python_sdk.paths.v1_source_id_customers_oid.delete import DeleteCustomerRaw
from baremetrics_python_sdk.paths.v1_source_id_plans_oid.delete import DeletePlanRaw
from baremetrics_python_sdk.paths.v1_source_id_charges_oid.get import GetChargeDetailsRaw
from baremetrics_python_sdk.paths.v1_source_id_charges.get import GetChargeListRaw
from baremetrics_python_sdk.paths.v1_source_id_customers_oid.get import GetCustomerDetailsRaw
from baremetrics_python_sdk.paths.v1_source_id_customers.get import GetCustomerListRaw
from baremetrics_python_sdk.paths.v1_source_id_events_id.get import GetEventByIdRaw
from baremetrics_python_sdk.paths.v1_source_id_events.get import GetEventsRaw
from baremetrics_python_sdk.paths.v1_source_id_plans_oid.get import GetPlanRaw
from baremetrics_python_sdk.paths.v1_source_id_plans.get import GetPlansListRaw
from baremetrics_python_sdk.paths.v1_source_id_refunds_oid.get import GetRefundDetailsRaw
from baremetrics_python_sdk.paths.v1_source_id_refunds.get import GetRefundsRaw
from baremetrics_python_sdk.paths.v1_source_id_subscriptions_oid.get import GetSubscriptionRaw
from baremetrics_python_sdk.paths.v1_source_id_subscriptions.get import GetSubscriptionsRaw
from baremetrics_python_sdk.paths.v1_source_id_customers_oid_events.get import ListCustomerEventsRaw
from baremetrics_python_sdk.paths.v1_sources.get import ListSourcesRaw
from baremetrics_python_sdk.paths.v1_source_id_charges_oid.delete import RemoveOneOffChargeRaw
from baremetrics_python_sdk.paths.v1_source_id_refunds_oid.delete import RemoveOneOffRefundRaw
from baremetrics_python_sdk.paths.v1_source_id_subscriptions_oid.delete import RemoveSubscriptionRaw
from baremetrics_python_sdk.paths.v1_source_id_customers_customer_oid.put import UpdateCustomerInformationRaw
from baremetrics_python_sdk.paths.v1_source_id_plans_plan_oid.put import UpdatePlanRaw
from baremetrics_python_sdk.paths.v1_source_id_subscriptions_subscription_oid.put import UpdateSubscriptionRaw


class SourceApiRaw(
    CancelSubscriptionRaw,
    CreateChargeOneOffRaw,
    CreateCustomerRecordRaw,
    CreateOneOffRefundRaw,
    CreatePlanRaw,
    CreateSubscriptionRaw,
    DeleteCustomerRaw,
    DeletePlanRaw,
    GetChargeDetailsRaw,
    GetChargeListRaw,
    GetCustomerDetailsRaw,
    GetCustomerListRaw,
    GetEventByIdRaw,
    GetEventsRaw,
    GetPlanRaw,
    GetPlansListRaw,
    GetRefundDetailsRaw,
    GetRefundsRaw,
    GetSubscriptionRaw,
    GetSubscriptionsRaw,
    ListCustomerEventsRaw,
    ListSourcesRaw,
    RemoveOneOffChargeRaw,
    RemoveOneOffRefundRaw,
    RemoveSubscriptionRaw,
    UpdateCustomerInformationRaw,
    UpdatePlanRaw,
    UpdateSubscriptionRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
