# coding: utf-8

"""
    Production

    Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class SourceCreateChargeOneOffRequest(BaseModel):
    # Your unique reference for this charge
    oid: str = Field(alias='oid')

    # The charge amount (in cents)
    amount: int = Field(alias='amount')

    # The ISO code of the currency of this plan. E.G: usd
    currency: str = Field(alias='currency')

    # Your unique ID for the customer
    customer_oid: str = Field(alias='customer_oid')

    # Unix timestamp of when this was created
    created: typing.Optional[datetime] = Field(None, alias='created')

    # The status of this charge. Can be paid or failed. Defaults to paid.
    status: typing.Optional[str] = Field(None, alias='status')

    fee: typing.Optional[int] = Field(None, alias='fee')

    # This can only be supplied when Subscription Auto Charging is disabled. Please contact support if you want to handle your subscription charges manually.
    subscription_oid: typing.Optional[str] = Field(None, alias='subscription_oid')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
