# coding: utf-8

"""
    Production

    Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class SourceCreateOneOffRefundRequest(BaseModel):
    # Your unique reference for this charge
    oid: str = Field(alias='oid')

    # The charge amount (in cents)
    amount: int = Field(alias='amount')

    # The ISO code of the currency of this plan. E.G: usd
    currency: str = Field(alias='currency')

    # Your unique ID for the customer
    customer_oid: str = Field(alias='customer_oid')

    # Which charge do you want to refund? This must be an API charge.
    charge_oid: str = Field(alias='charge_oid')

    # Unix timestamp of when this was created
    created: typing.Optional[datetime] = Field(None, alias='created')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
