# coding: utf-8

"""
    Production

    Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect.   In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster:   Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit.   Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.  Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from baremetrics_python_sdk.pydantic.source_get_refund_details_response_customer import SourceGetRefundDetailsResponseCustomer

class SourceGetRefundDetailsResponse(BaseModel):
    oid: typing.Optional[str] = Field(None, alias='oid')

    source_id: typing.Optional[str] = Field(None, alias='source_id')

    source: typing.Optional[str] = Field(None, alias='source')

    charge_oid: typing.Optional[str] = Field(None, alias='charge_oid')

    created: typing.Optional[int] = Field(None, alias='created')

    customer: typing.Optional[SourceGetRefundDetailsResponseCustomer] = Field(None, alias='customer')

    amount: typing.Optional[int] = Field(None, alias='amount')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
